spring:
  profiles:
    active:
    # - native
    # - development
     - remote_repo
 
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
          - C:/config-repo
--- 

spring:        
  profiles: development
  
# using git/local file system 

  cloud:
    config:
      server:
        git:
          uri: file:///C:/config-repo

---

spring:        
  profiles: remote_repo
  
# using git/local file system 

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sureshpec04/cloud-config-repo
          skip-ssl-validation: true
          #username: githubusername
          #password: repopassword

---

server:
  port: 8888
  
